// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

// CreateChirp implements the query defined in sql/queries/chirps.sql
func (q *Queries) CreateChirp(ctx context.Context, params CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, `
		INSERT INTO chirps (id, created_at, updated_at, body, user_id)
		VALUES (
			gen_random_uuid(),
			NOW(),
			NOW(),
			$1,
			$2
		)
		RETURNING id, created_at, updated_at, body, user_id
	`, params.Body, params.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
} 